[versions]
autoService = "1.1.1"
binaryCompatibilityValidator = "0.17.0"
jdk = "21"
jvmTarget = "17"
kotlin = "2.3.0"
kotlinCompileTesting = "0.12.1"
mavenPublish = "0.36.0"
moshi = "1.15.2"
testkitLibs = "0.22"
testkitTruthVersion = "1.6.1"
testkitPlugin = "0.17"

[libraries]
# Google's AutoService (optional - for compatibility only)
autoService = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }

kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePluginApi = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }

# Test libs
junit4 = { module = "junit:junit", version = "4.13.2" }
junit5-bom = { module = "org.junit:junit-bom", version = "5.11.4" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit5-launcher = { module = "org.junit.platform:junit-platform-launcher" }
truth = { module = "com.google.truth:truth", version = "1.4.5" }
kotlinCompileTesting = { module = "dev.zacsweers.kctfork:core", version.ref = "kotlinCompileTesting" }
autonomousapps-testkit-support = { module = "com.autonomousapps:gradle-testkit-support", version.ref = "testkitLibs" }
autonomousapps-testkit-truth = { module = "com.autonomousapps:gradle-testkit-truth", version.ref = "testkitTruthVersion" }
autonomousapps-testkitPlugin = { module = "com.autonomousapps:gradle-testkit-plugin", version.ref = "testkitPlugin" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

# Convention plugin dependencies
kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
vanniktech-mavenPublish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenPublish" }

