name: "Test"

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildHealth:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Health
      run: ./gradlew :buildHealth

  functionalTest:
    name: functionalTest (Kotlin ${{ matrix.kotlin_version }}, Gradle ${{ matrix.gradle_version }})
    strategy:
      matrix:
        kotlin_version:
          - 2.3.10
        gradle_version:
          - 8.14.3
          - 9.3.1
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Functional Tests
      run: ./gradlew functionalTest -DgradleVersion=${{ matrix.gradle_version }} -DkotlinVersion=${{ matrix.kotlin_version }}

  functionalTest-results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: functionalTest Results
    needs: [functionalTest]
    steps:
      - run: |
          result="${{ needs.functionalTest.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi

  compilerTest:
    name: compilerTest (Kotlin ${{ matrix.kotlin_version }})
    strategy:
      matrix:
        kotlin_version:
          - 2.3.10
          - 2.3.20-RC
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Compiler Plugin Tests
      run: ./gradlew :compiler-plugin:test -DkotlinVersion=${{ matrix.kotlin_version }}

  compilerTest-results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: compilerTest Results
    needs: [compilerTest]
    steps:
      - run: |
          result="${{ needs.compilerTest.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
